# Generated by Django 2.2.7 on 2019-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('ThumbnailAltText', models.CharField(blank=True, max_length=50, null=True)),
                ('weakness', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('collectibles_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.BooleanField(default='True')),
                ('ThumbnailImage', models.CharField(blank=True, max_length=50, null=True)),
                ('threat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
