# Generated by Django 2.2.7 on 2019-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='ThumbnailImage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='threat_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
